/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_MACH_MEDIATEk_KMALLOC_H
#define __ASM_MACH_MEDIATEK_KMALLOC_H

#define ARCH_DMA_MINALIGN	L1_CACHE_BYTES

#endif /* __ASM_MACH_MEDIATEK_KMALLOC_H */
